/* Asif Mahmud, C0837117 */

/* 1 */
SELECT 
  RENTAL_FEE AS "Fee", 
  SLIP_CODE AS "Slip",
  BOAT_NAME AS "Boat Name"
FROM M_MARINA_SLIPS 
WHERE MARINA_ID = 1 AND SLIP_LENGTH BETWEEN 25 AND 30
ORDER BY RENTAL_FEE DESC;


/* 2 */
SELECT 
  MARINA_ID,
  RENTAL_FEE, 
  SLIP_CODE,
  BOAT_NAME
FROM M_MARINA_SLIPS 
WHERE 
  MARINA_ID = 1 AND RENTAL_FEE > 3000 OR
  MARINA_ID = 2 AND RENTAL_FEE < 4000
ORDER BY MARINA_ID, RENTAL_FEE;


/* 3 */
SELECT 
  MARINA_ID,
  SLIP_LENGTH,
  BOAT_NAME
FROM M_MARINA_SLIPS 
WHERE 
  BOAT_TYPE IN ('Sprite 4000', 'Sprite 3000', 'Ray 4025')
ORDER BY MARINA_ID, SLIP_LENGTH DESC, BOAT_NAME;


/* 4 */
SELECT 
  BOAT_NAME AS "Boat Name",
  '$ ' || TO_CHAR(RENTAL_FEE, '9,999.99') AS "Old Rental Fee",
  '$ ' || TO_CHAR((RENTAL_FEE * 1.0875), '9,999.99') AS "New Rental Fee"
FROM M_MARINA_SLIPS 
WHERE 
  (RENTAL_FEE * 1.0875) > 4000
ORDER BY "New Rental Fee" DESC;

/* 5 */
SELECT 
  SLIP_CODE AS "Slip",
  TO_CHAR(NEXT_SERVICE_DATE, 'Day, Month, dd, yyyy') 
FROM M_SERVICE_REQUESTS
WHERE 
  YEAR(NEXT_SERVICE_DATE) >= :Enter_year 
ORDER BY "Slip";


/* 6 */
SELECT 
  MARINA_ID AS "Marina",
  CASE
    WHEN RENTAL_FEE >= 4200 THEN 'Gold customer'
    WHEN RENTAL_FEE BETWEEN 3600 AND 4199 THEN 'Silver customer'
    WHEN RENTAL_FEE BETWEEN 2000 AND 3599 THEN 'Bronze customer'
    WHEN RENTAL_FEE BETWEEN 0 AND 1999 THEN 'Not Categorized'
  END AS "Category",
  RENTAL_FEE AS "Fee",
  SLIP_CODE AS "Slip" 
FROM M_MARINA_SLIPS
ORDER BY MARINA_ID, "Category", RENTAL_FEE;

/* 7 */
SELECT 
  BOAT_NAME,
  SLIP_LENGTH,
  CEIL(RENTAL_FEE) AS rental_fee 
FROM M_MARINA_SLIPS
WHERE 
  CEIL(RENTAL_FEE) >= 3800
ORDER BY BOAT_NAME;


/* 8 */
SELECT 
  SLIP_CODE,
  EST_HOURS,
  TO_CHAR(EST_HOURS * 119.999, '999.99') AS estimated_cost
FROM M_SERVICE_REQUESTS
WHERE 
  TO_CHAR(EST_HOURS * 119.999, '999.99') >= 300
ORDER BY estimated_cost DESC;


/* 9 */
SELECT 
  SUBSTRING(FIRST_NAME, 1, 1) || '. ' || UPPER(LAST_NAME) AS owner_name
FROM M_PREVIOUS_OWNERS
WHERE 
  LOWER(FIRST_NAME||LAST_NAME) LIKE '%and%'
ORDER BY LAST_NAME;


/* 10 */
SELECT 
  TO_CHAR(MIN(RENTAL_FEE),'9,999.99') AS "Lowest fee",
  TO_CHAR(MAX(RENTAL_FEE),'9,999.99') AS "Highest fee",
  TO_CHAR(AVG(RENTAL_FEE),'9,999.99') AS "Average fee",
  '$ ' || TO_CHAR(SUM(RENTAL_FEE),'99,999.99') AS "Total rental fees"
FROM M_MARINA_SLIPS
WHERE 
  MARINA_ID = 2
GROUP BY 
  MARINA_ID;


/* 11 */
SELECT 
  MARINA_ID,
  SLIP_CODE,
  COALESCE(BOAT_NAME, 'No boat assigned')
FROM M_MARINA_SLIPS
WHERE 
  MARINA_ID IN (1,3)
ORDER BY MARINA_ID, SLIP_CODE DESC;


/* 12 */
SELECT 
  MARINA_ID,
  SLIP_LENGTH,
  COUNT(*) AS "COUNT",
  TO_CHAR(SUM(RENTAL_FEE), '99,999.99') AS yearly_revenue 
FROM M_MARINA_SLIPS
WHERE 
  MARINA_ID IN (1,2)
GROUP BY
  MARINA_ID, SLIP_LENGTH 
ORDER BY MARINA_ID, SLIP_LENGTH;

