/* Name: Asif Mahmud, ID: #C0837117 */

/* 1 */
SELECT 
  MARINA_NAME,
  SLIP_LENGTH,
  BOAT_NAME,
  RENTAL_FEE
FROM M_MARINAS
JOIN M_MARINA_SLIPS USING(MARINA_ID)
ORDER BY MARINA_NAME, SLIP_LENGTH

/* 2 */
SELECT 
  m.MARINA_NAME,
  o.LAST_NAME || ', ' || o.FIRST_NAME AS OWNER,
  s.BOAT_NAME
FROM M_MARINAS m
JOIN M_MARINA_SLIPS s USING(MARINA_ID)
JOIN M_OWNERS o USING(OWNER_CODE)
WHERE o.CITY = 'Bowton' AND s.SLIP_LENGTH = 40
ORDER BY MARINA_NAME, OWNER

/* 3 */
SELECT 
  SLIP_CODE,
  BOAT_NAME,
  LAST_NAME,
  CATEGORY_DESCRIPTION,
  EST_HOURS
FROM M_MARINA_SLIPS ms
JOIN M_OWNERS o USING(OWNER_CODE)
JOIN M_SERVICE_REQUESTS msr USING(SLIP_CODE)
JOIN M_SERVICE_CATEGORIES msc USING(CATEGORY_ID)
WHERE CATEGORY_ID = 2
ORDER BY SLIP_CODE;

/* 4 */
SELECT 
  ms.SLIP_CODE,
  BOAT_NAME,
  COALESCE(TO_CHAR(EST_HOURS, '0.99'), '') AS EST_HOURS,
  COALESCE(TO_CHAR(SPENT_HOURS, '0.99'), '') AS SPENT_HOURS,
  COALESCE(TO_CHAR(msr.CATEGORY_ID, '9'), '') AS CATEGORY_ID,
  COALESCE(CATEGORY_DESCRIPTION, '') AS CATEGORY_DESCRIPTION
FROM M_MARINA_SLIPS ms
LEFT JOIN M_SERVICE_REQUESTS msr ON(ms.SLIP_CODE = msr.SLIP_CODE)
LEFT JOIN M_SERVICE_CATEGORIES msc ON(msr.CATEGORY_ID = msc.CATEGORY_ID)
WHERE MARINA_ID = 2
ORDER BY SLIP_CODE;

/* 5 */
SELECT 
  MARINA_ID,
  SLIP_CODE,
  COALESCE(BOAT_NAME, 'Slip not rented') AS boat_name,
  COALESCE(FIRST_NAME || ' ' || LAST_NAME, '') AS owner_name
FROM M_MARINAS 
JOIN M_MARINA_SLIPS USING(MARINA_ID)
LEFT JOIN M_OWNERS USING(OWNER_CODE)
ORDER BY SLIP_CODE;

/* 6 */
SELECT 
  MARINA_ID,
  SLIP_LENGTH,
  COUNT(*) AS count,
  TO_CHAR(SUM(RENTAL_FEE), '99,999.99') AS YEARLY_REVENUE
FROM M_MARINAS m
JOIN M_MARINA_SLIPS mms USING(MARINA_ID)
GROUP BY SLIP_LENGTH, MARINA_ID
ORDER BY MARINA_ID, SLIP_LENGTH;

/* 7 */
SELECT 
  MARINA_ID,
  SLIP_LENGTH,
  COUNT(*) AS count,
  TO_CHAR(SUM(RENTAL_FEE), '99,999.99') AS YEARLY_REVENUE
FROM M_MARINAS m
JOIN M_MARINA_SLIPS mms USING(MARINA_ID)
GROUP BY SLIP_LENGTH, MARINA_ID
HAVING (MARINA_ID = 1 OR MARINA_ID = 3) AND SUM(RENTAL_FEE) >= 2500
ORDER BY MARINA_ID, SLIP_LENGTH;

/* 8 */
CREATE OR REPLACE VIEW T2V AS
  SELECT
    o.CITY,
    o.LAST_NAME || ', ' || o.FIRST_NAME AS OWNER,
    BOAT_NAME,
    SLIP_LENGTH,
    RENTAL_FEE
  FROM LCPUBLIC.M_OWNERS o
  JOIN LCPUBLIC.M_MARINA_SLIPS mms USING(OWNER_CODE)
  WHERE MARINA_ID = 2 AND RENTAL_FEE > 1800

SELECT * FROM T2V
  
/* 9 */
SELECT 
  OWNER,
  BOAT_NAME,
  RENTAL_FEE
FROM T2V
WHERE SLIP_LENGTH > 25
ORDER BY OWNER DESC;


/* 10 */
SELECT
  o.LAST_NAME || ', ' || o.FIRST_NAME AS OWNER,
  BOAT_NAME,
  RENTAL_FEE
FROM M_OWNERS o
JOIN M_MARINA_SLIPS mms USING(OWNER_CODE)
WHERE MARINA_ID = 2 AND RENTAL_FEE > 1800 AND SLIP_LENGTH > 25
ORDER BY OWNER DESC

/* 11 */
SELECT 
  o.LAST_NAME || ', ' || o.FIRST_NAME AS OWNER_NAME,
  o.CITY,
  MARINA_ID,
  SLIP_CODE,
  RENTAL_FEE
FROM M_OWNERS o
JOIN M_MARINA_SLIPS mms USING(OWNER_CODE)
WHERE RENTAL_FEE > ALL(
  SELECT AVG(RENTAL_FEE)
  FROM M_MARINA_SLIPS
)
ORDER BY OWNER_NAME

/* 12 */ 
SELECT 
  MARINA_ID,
  SLIP_CODE,
  o.FIRST_NAME || ' ' || o.LAST_NAME AS OWNER_NAME,
  o.CITY,
  RENTAL_FEE
FROM M_OWNERS o
JOIN M_MARINA_SLIPS mms USING(OWNER_CODE)
WHERE RENTAL_FEE > (
  SELECT AVG(RENTAL_FEE)
  FROM M_MARINA_SLIPS mms2
  WHERE mms.MARINA_ID = mms2.MARINA_ID 
)
ORDER BY MARINA_ID, SLIP_CODE
