/* 1 */
SELECT CUSTOMER_NAME, UPPER(STREET || ', ' || CUST_STATE || ' ' || ZIP) AS "Customer Address"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('WI', 'SC', 'NY')
ORDER BY CUSTOMER_NAME;

/* 2 */
SELECT LOWER(LAST_NAME || ', ' || FIRST_NAME) AS "FIRST_NAME", LOWER(STREET || ' ' || CITY || ', ' || EMP_STATE || ' ' || ZIP) AS "Address"
FROM B_EMPLOYEES
ORDER BY LAST_NAME;

/* 3 */
SELECT LAST_NAME 
  CONCAT ' '
  CONCAT STREET
  CONCAT ' '
  CONCAT CITY
  CONCAT ', '
  CONCAT EMP_STATE
  CONCAT ' '
  CONCAT ZIP
  AS "Employee's Address"
FROM B_EMPLOYEES
ORDER BY LAST_NAME;

/* 4 */
SELECT CONCAT('Data', 'base') AS "TITLE"
FROM SYSIBM.SYSDUMMY1;

/* 5 */
SELECT SUBSTR(FIRST_NAME, 1, 1) || '. ' || LAST_NAME 
FROM B_EMPLOYEES
ORDER BY LAST_NAME DESC;


/* 6 */
SELECT SUBSTR(FIRST_NAME, 1, 1) || '. ' || LAST_NAME, COMMISSION 
FROM B_EMPLOYEES
WHERE SUPERVISOR_ID = (:SUPERVISOR_ID)
ORDER BY LAST_NAME DESC

/* 7 */
SELECT INSTR('Database Design and SQL.', 'Q') AS "POSITION"
FROM SYSIBM.SYSDUMMY1;

/* 8 */
SELECT LENGTH('Database Design and SQL.') AS "Length"
FROM SYSIBM.SYSDUMMY1;

/* 9 */
SELECT LTRIM('    Database') || ' ' || RTRIM('Design    ') || ' ' || TRIM('    and SQL   ') AS "TITLE"
FROM SYSIBM.SYSDUMMY1;

/* 10 */
SELECT LPAD('Database', 12, '*') || LPAD('Internet', 12, '*') || LPAD(RPAD('Academy', 11, '*'), 15, '*') AS "DIA"
FROM SYSIBM.SYSDUMMY1;

/* 11 */
SELECT RPAD('Database', 11, '$') || RPAD('Internet', 11, '$') || 'Academy' AS "DIA"
FROM SYSIBM.SYSDUMMY1;

/* 12 */
SELECT REPLACE('Database Internet Academy', 'Internet', '2021-2022') AS "COURSE"
FROM SYSIBM.SYSDUMMY1;

/* 13 */
SELECT PRODUCT_CODE, LPAD(PRICE_PAID, 9, '$') AS "PRICE" 
FROM B_ORDER_LINES
WHERE PRICE_PAID > 400
ORDER BY PRODUCT_CODE, PRICE_PAID DESC;

/* 14 */
SELECT PRODUCT_CODE, DESCRIPTION, PRICE
FROM B_PRODUCTS
WHERE CATEGORY_CODE = UPPER(:CATEGORY_CODE) 
  AND PRICE BETWEEN 2400 AND 6000
ORDER BY PRODUCT_CODE;