/* 1 */
SELECT
  CUST_STATE AS "State",
  COUNT(CUSTOMER_ID) AS "Customer Count",
  TO_CHAR(AVG(BALANCE),'99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CA', 'MI', 'SC', 'TX')
GROUP BY CUST_STATE
ORDER BY CUST_STATE;

/* 2 */
SELECT
  CUST_STATE AS "State",
  CITY AS "City",
  COUNT(CUSTOMER_ID) AS "Customer Count",
  TO_CHAR(AVG(BALANCE),'99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CO', 'NV')
GROUP BY CUST_STATE, CITY 
ORDER BY CUST_STATE;

/* 3 */
SELECT
  YEAR(MEMBERSHIP_DATE) AS "Year",
  MONTH(MEMBERSHIP_DATE) AS "Month",
  COUNT(CUSTOMER_ID) AS "Customer Count"
FROM B_CUSTOMERS
GROUP BY YEAR(MEMBERSHIP_DATE), MONTH(MEMBERSHIP_DATE)
ORDER BY "Year", "Month";

/* 4 #*/
SELECT
  CUST_STATE AS "State",
  CITY AS "City",
  COUNT(CUSTOMER_ID) AS "Customer Count",
  TO_CHAR(AVG(BALANCE),'99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
GROUP BY CUST_STATE, CITY
HAVING AVG(BALANCE) BETWEEN 30000 AND 50000
ORDER BY CUST_STATE, CITY;

/* 5 */
SELECT
  CUST_STATE AS "State",
  CITY AS "City",
  COUNT(CUSTOMER_ID) AS "Customer Count",
  TO_CHAR(AVG(BALANCE),'99,999.99') AS "Average Balance"
FROM B_CUSTOMERS
WHERE CUST_STATE IN ('CO', 'NV', 'NY', 'SC', 'WI')
GROUP BY CUST_STATE, CITY
HAVING AVG(BALANCE) BETWEEN 20000 AND 30000
ORDER BY CUST_STATE, CITY;

/* 6 */
SELECT 
  CATEGORY_CODE,
  TO_CHAR(AVG(PRICE),'9999.99') AS "Average price"
FROM B_PRODUCTS
GROUP BY CATEGORY_CODE 
HAVING AVG(PRICE) > 1500
ORDER BY CATEGORY_CODE;
