/* Name: Asif Mahmd, ID: C0837117 */

/* 1 */
SELECT BALANCE, CUSTOMER_NAME
FROM S1_CUSTOMERS
WHERE
  SHIP_CITY IN ('Albany', 'Boston', 'Toronto') AND 
  BALANCE BETWEEN 1150 AND 2000
ORDER BY BALANCE DESC;

/* 2 */
SELECT CUSTOMER_NAME
FROM S1_CUSTOMERS
WHERE
  (CREDIT_LIMIT > 125000 AND BALANCE > 2000) OR
  (CREDIT_LIMIT - BALANCE > 150000)
ORDER BY CUSTOMER_NAME;

/* 3 */
SELECT 
  CUSTOMER_NAME, 
  CREDIT_LIMIT AS "Credit Limit",
  BALANCE AS "Balance",
  CREDIT_LIMIT - BALANCE AS "Available Credit"
FROM S1_CUSTOMERS
WHERE
  CREDIT_LIMIT - BALANCE > 100000
ORDER BY "Available Credit" DESC;


/* 4 */
SELECT
  SUBSTR(FIRST_NAME,1,1) || '. ' || M_INITIAL || '. ' || LAST_NAME AS "Employee",
  TO_CHAR(BIRTH_DATE, 'Mon, dd, yyyy') AS "Birth Date",
  TO_CHAR(HIRE_DATE, 'Day, Month, dd, yyyy') AS "Hire Date",
  TO_CHAR((DAYS('2021-01-01') - DAYS(HIRE_DATE )) /365.2425, '99.99') AS "Years of Service" 
FROM S1_EMPLOYEES 
WHERE (DAYS('2021-01-01') - DAYS(HIRE_DATE )) /365.2425 >= 10
ORDER BY "Years of Service";


/* 5 */
SELECT 
  CASE
    WHEN CREDIT_LIMIT >= 200000 THEN '1 Gold customer'
    WHEN CREDIT_LIMIT BETWEEN 160000 AND 199999 THEN '2 Silver customer'
    WHEN CREDIT_LIMIT BETWEEN 135000 AND 159999 THEN '3 Bronze customer'
    WHEN CREDIT_LIMIT BETWEEN 105000 AND 134999 THEN '4 Not categorized'
    ELSE '4 Not categorized'
  END AS "Category",
  CUSTOMER_NAME AS "Customer"
FROM S1_CUSTOMERS
ORDER BY "Category", CUSTOMER_NAME 


/* 6 */
SELECT 
  TO_CHAR(MIN(SALARY), '9,999.99') AS "Lowest salary",
  TO_CHAR(MAX(SALARY), '99,999.99') AS "Highest salary",
  TO_CHAR(AVG(SALARY), '99,999.99') AS "Average salary",
  TO_CHAR(SUM(SALARY), '9,999,999.99') AS "Total salary" 
FROM S1_EMPLOYEES


/* 7 */
SELECT CUSTOMER_NAME, COALESCE(TO_CHAR(DISCOUNT, '9.999'), 'No discount assigned') AS "DISCOUNT"
FROM S1_CUSTOMERS
WHERE CREDIT_LIMIT > 150000
ORDER BY CUSTOMER_NAME ;


/* 8 */
SELECT FIRST_NAME || ' ' || M_INITIAL || '. ' || LAST_NAME AS "Employee"
FROM S1_EMPLOYEES
WHERE EMP_ID < 106
ORDER BY LAST_NAME 

/* NOTE: Because the first name and the last name of the first employee is not capitalized */


/* 9 */
SELECT CUSTOMER_NAME 
FROM S1_CUSTOMERS
WHERE INSTR(CUSTOMER_NAME, 'Steel') > 0
ORDER BY CUSTOMER_NAME;


/* 10 */
SELECT 
  FIRST_NAME || ' ' || LAST_NAME AS "EMPLOYEE",
  HIRE_DATE 
FROM S1_EMPLOYEES
WHERE YEAR(HIRE_DATE) = '2016'
ORDER BY HIRE_DATE, LAST_NAME;


/* 11 */
SELECT 
  FIRST_NAME || ' ' || LAST_NAME AS "EMPLOYEE",
  HIRE_DATE 
FROM S1_EMPLOYEES
WHERE HIRE_DATE BETWEEN (:Enter_start_date) AND (:Enter_end_date)
ORDER BY HIRE_DATE, LAST_NAME;


/* 12 */
SELECT 
  STORE_ID,
  WORK_DEPT_ID AS "Dept",
  COUNT(*) AS "Count",
  TO_CHAR(MAX(SALARY),'99999.99') AS "Highest Salary",
  TO_CHAR(AVG(SALARY), '99999.99') AS "Average Salary"
FROM S1_EMPLOYEES
GROUP BY STORE_ID, WORK_DEPT_ID 
ORDER BY STORE_ID, WORK_DEPT_ID;


/* 13 */
SELECT 
  STORE_ID,
  WORK_DEPT_ID AS "Dept",
  COUNT(*) AS "Count",
  TO_CHAR(MAX(SALARY),'99999.99') AS "Highest Salary",
  TO_CHAR(AVG(SALARY), '99999.99') AS "Average Salary"
FROM S1_EMPLOYEES
GROUP BY STORE_ID, WORK_DEPT_ID 
HAVING AVG(SALARY) > 45000
ORDER BY STORE_ID, WORK_DEPT_ID;


/* 14 */
SELECT 
  FIRST_NAME || ' ' || LAST_NAME AS Employee,
  HIRE_DATE,
  TO_CHAR(MONTHS_BETWEEN('2020-01-01', HIRE_DATE), '999.99') AS "MONTHS_WORKED"
FROM S1_EMPLOYEES
WHERE MONTHS_BETWEEN('2020-01-01', HIRE_DATE) > 100
ORDER BY MONTHS_WORKED DESC;