/* 1 */
SELECT PUBLISHER_NAME
FROM H_PUBLISHERS 
WHERE CITY = 'Boston'
ORDER BY PUBLISHER_NAME;

/* 2 */
SELECT BOOK_CODE, TITLE 
FROM H_BOOKS
WHERE "TYPE" = 'HOR' AND PAPERBACK = 'Y'
ORDER BY BOOK_CODE;

/* 3 */
SELECT BOOK_CODE, TITLE 
FROM H_BOOKS
WHERE "TYPE" = 'HOR' OR PUBLISHER_CODE = 'SC'
ORDER BY BOOK_CODE;

/* 4 */
SELECT DISTINCT "TYPE" 
FROM H_BOOKS
ORDER BY "TYPE";

/* 5 */
SELECT PUBLISHER_NAME
FROM H_PUBLISHERS
WHERE CITY NOT IN('New York')
ORDER BY PUBLISHER_NAME;

/* 6 */
SELECT BRANCH_NAME 
FROM H_BRANCHES
WHERE NBR_EMPLOYEES >= 10
ORDER BY BRANCH_NAME;

/* 7 */
SELECT 
  AUTHOR_ID, 
  LOWER(AUTHOR_FIRST) AS first_name, 
  UPPER(AUTHOR_LAST) AS last_name 
FROM H_AUTHORS
ORDER BY AUTHOR_LAST;

/* 8 */
SELECT UPPER(SUBSTRING(AUTHOR_FIRST, 1)) || ' ' || UPPER(AUTHOR_LAST) AS "AUTHOR_NAME" 
FROM H_AUTHORS
WHERE AUTHOR_LAST LIKE 'C%'
ORDER BY AUTHOR_LAST, AUTHOR_FIRST;

/* 9 */
SELECT TITLE 
FROM H_BOOKS
WHERE LOWER(TITLE) LIKE '%the%'
ORDER BY TITLE;

/* 10 */
SELECT
  BOOK_CODE,
  TITLE,
  PRICE AS old_price,
  DECIMAL(ROUND(PRICE,0),4,2) AS new_price 
FROM H_BOOKS
WHERE DECIMAL(ROUND(PRICE,0),4,2) = 7.00
ORDER BY BOOK_CODE;

/* 11 */
SELECT
  BOOK_CODE,
  TITLE,
  PRICE AS old_price,
  DECIMAL(ROUND(ROUND(PRICE,1),0),4,2) AS new_price 
FROM H_BOOKS
WHERE DECIMAL(ROUND(ROUND(PRICE,1),0),4,2) >= 25.00
ORDER BY BOOK_CODE;

/* 12 */
SELECT 
  TITLE,
  PRICE AS regular_price,
  DECIMAL(FLOOR(PRICE), 4,2) AS sale_price 
FROM H_BOOKS
WHERE FLOOR(PRICE) > 17.00 
ORDER BY PRICE DESC;

/* 13 */
SELECT 
  BOOK_CODE, 
  TITLE,
  PRICE 
FROM H_BOOKS
WHERE PRICE BETWEEN 21 AND 25
ORDER BY PRICE DESC;

/* 14 */
SELECT 
  BOOK_CODE, 
  TITLE,
  PRICE 
FROM H_BOOKS
WHERE "TYPE" = 'FIC' AND PRICE > 12.00
ORDER BY PRICE DESC, BOOK_CODE;

/* 15 */
SELECT 
  BOOK_CODE, 
  TITLE,
  PRICE AS original_price,
  DECIMAL(0.1*ROUND(PRICE,1),3,2) AS discount,
  DECIMAL(PRICE - 0.1*ROUND(PRICE,1),4,2) AS discounted_price
FROM H_BOOKS
WHERE PRICE - 0.1*ROUND(PRICE,1) > 22.00
ORDER BY discounted_price;

/* 16 */
SELECT PUBLISHER_NAME 
FROM H_PUBLISHERS
WHERE PUBLISHER_NAME LIKE '% and %'
ORDER BY PUBLISHER_NAME;

/* 17 */
SELECT
  "TYPE",
  PRICE,
  TITLE 
FROM H_BOOKS
WHERE "TYPE" IN ('FIC', 'PHI', 'POE')
ORDER BY "TYPE", PRICE DESC, TITLE;

/* 18 */
SELECT 
  TITLE AS "Book Title",
  PRICE AS "Price",
  CASE 
    WHEN PAPERBACK = 'Y' THEN 'Paperback'
    WHEN PAPERBACK = 'N' THEN 'Hardcover'
  END AS "Cover"
FROM H_BOOKS
WHERE ((PRICE BETWEEN 8 AND 12) AND PAPERBACK = 'Y')
  OR ((PRICE BETWEEN 18 AND 21) AND PAPERBACK = 'N')
ORDER BY PRICE DESC;

/* 19 */
SELECT
  TITLE,
  TO_CHAR(PUBLISHED_DATE, 'Day, Month, dd, yyyy') AS pub_date
FROM H_BOOKS
WHERE PUBLISHED_DATE BETWEEN (DATE('2018-03-01') - 20 MONTHS) AND '2018-03-01'
ORDER BY TITLE 

/* 20 */
SELECT
  PUBLISHED_DATE,
  TITLE 
FROM H_BOOKS
WHERE PUBLISHED_DATE > '2016-01-01'
ORDER BY PUBLISHED_DATE, TITLE 

/* 21 */
SELECT
  YEAR(PUBLISHED_DATE) AS pub_year,
  TITLE 
FROM H_BOOKS
ORDER BY pub_year, TITLE;

/* 22 */
SELECT
  TITLE,
  DECIMAL(ROUND(MONTHS_BETWEEN(CURRENT_DATE, PUBLISHED_DATE),0),3,0) AS months_published
FROM H_BOOKS
ORDER BY TITLE;

/* 23 */
SELECT 
  DECIMAL(MIN(PRICE),3,2) AS "Lowest",
  DECIMAL(MAX(PRICE),4,2) AS "Highest",
  DECIMAL(AVG(PRICE),4,2) AS "Average",
  DECIMAL(SUM(PRICE),5,2) AS "Total price"
FROM H_BOOKS;

/* 24 */
SELECT 
  TITLE,
  PUBLISHED_DATE 
FROM H_BOOKS
WHERE PUBLISHED_DATE BETWEEN :Enter_start_date AND :Enter_end_date
ORDER BY PUBLISHED_DATE;

/* 25 */
SELECT 
  PUBLISHER_CODE, 
  BOOK_CODE,
  TITLE,
  PRICE AS old_price,
  DECIMAL(CEIL(PRICE), 4, 2) AS new_price
FROM H_BOOKS
WHERE PUBLISHER_CODE IN ('BP', 'JP', 'TB')
ORDER BY new_price, BOOK_CODE ;

/* 26 */
SELECT 
  PUBLISHER_CODE, 
  BOOK_CODE,
  TITLE,
  PRICE AS old_price,
  DECIMAL(FLOOR(PRICE), 4, 2) AS new_price
FROM H_BOOKS
WHERE PUBLISHER_CODE IN ('BP', 'JP', 'TB')
ORDER BY new_price, BOOK_CODE ;

/* 27 */
SELECT 
  PUBLISHER_CODE, 
  "TYPE",
  COUNT(*),
  TO_CHAR(AVG(PRICE), '99.99') AS average_price
FROM H_BOOKS
WHERE PUBLISHER_CODE IN ('LB', 'PE', 'PL', 'JP', 'SC')
GROUP BY PUBLISHER_CODE, "TYPE"
ORDER BY PUBLISHER_CODE, "TYPE";

/* 28 */
SELECT 
  PUBLISHER_CODE, 
  "TYPE",
  COUNT(*),
  TO_CHAR(AVG(PRICE), '99.99') AS average_price
FROM H_BOOKS
WHERE PUBLISHER_CODE IN ('LB', 'PE', 'PL', 'JP', 'SC')
GROUP BY PUBLISHER_CODE, "TYPE"
HAVING AVG(PRICE) >= 12
ORDER BY PUBLISHER_CODE, "TYPE";

/* 29 */
SELECT 
  TITLE,
  PRICE,
  PUBLISHED_DATE,
  DECIMAL((DAYS('2021-01-01')-DAYS(PUBLISHED_DATE))/365.2425, 4, 2) AS "Years published"
FROM H_BOOKS
WHERE DECIMAL((DAYS('2021-01-01')-DAYS(PUBLISHED_DATE))/365.2425, 4,2) >= 15
ORDER BY "Years published";

/* 30 */
SELECT 
  TITLE AS "Book title",
  PRICE AS "Book price",
  TO_CHAR(PUBLISHED_DATE, 'Month yyyy') AS "Published date"
FROM H_BOOKS
WHERE PUBLISHED_DATE BETWEEN :Enter_start_date AND :Enter_end_date
ORDER BY PUBLISHED_DATE, TITLE;

