/* 1 */
SELECT 
  e.EMPLOYEE_ID AS "EM#",
  e.FIRST_NAME || ' ' || e.LAST_NAME AS employee,
  m.FIRST_NAME || ' ' || m.LAST_NAME AS manager,
  m.EMPLOYEE_ID AS "MGR#"
FROM B_EMPLOYEES e
INNER JOIN B_EMPLOYEES m
ON (e.MANAGER_ID = m.EMPLOYEE_ID)
ORDER BY e.EMPLOYEE_ID;


/* 2 */
SELECT 
  e.EMPLOYEE_ID AS "EM#",
  e.FIRST_NAME || ' ' || e.LAST_NAME AS employee,
  COALESCE(m.FIRST_NAME || ' ' || m.LAST_NAME, 'Not assigned') AS manager,
  COALESCE(TO_CHAR(m.EMPLOYEE_ID, '999'), ' ---') AS "MGR#"
FROM B_EMPLOYEES e
LEFT JOIN B_EMPLOYEES m
ON (e.MANAGER_ID = m.EMPLOYEE_ID)
ORDER BY e.EMPLOYEE_ID;


/* 3 */
SELECT 
  m.EMPLOYEE_ID AS "MGR#",
  m.FIRST_NAME || ' ' || m.LAST_NAME AS manager,
  e.EMPLOYEE_ID AS "EM#",
  e.FIRST_NAME || ' ' || e.LAST_NAME AS employee
FROM B_EMPLOYEES e
LEFT JOIN B_EMPLOYEES m
ON (m.EMPLOYEE_ID = e.MANAGER_ID)
WHERE 
  e.MANAGER_ID IN (110,111,112)
ORDER BY e.MANAGER_ID, m.EMPLOYEE_ID;


/* 4 */
SELECT 
  e.FIRST_NAME || ' ' || e.LAST_NAME AS employee,
  e.HIRE_DATE AS emp_hire_date,
  m.FIRST_NAME || ' ' || m.LAST_NAME AS manager,
  m.HIRE_DATE AS mgr_hire_date 
FROM B_EMPLOYEES e
INNER JOIN B_EMPLOYEES m
ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE e.HIRE_DATE < m.HIRE_DATE 
ORDER BY e.LAST_NAME;

/* 5 */
SELECT 
  DEPARTMENT_NAME,
  FIRST_NAME || ' ' || LAST_NAME AS employee_name,
  JOB_TITLE
FROM B_DEPARTMENTS
INNER JOIN B_EMPLOYEES USING(DEPARTMENT_CODE)
INNER JOIN B_JOBS USING(JOB_CODE)
ORDER BY DEPARTMENT_NAME, LAST_NAME;


/* 6 */
SELECT 
  CUSTOMER_NAME,
  ORDER_ID,
  SUM(PRICE_PAID*QUANTITY) AS order_total
FROM B_CUSTOMERS
JOIN B_ORDERS USING(CUSTOMER_ID)
JOIN B_ORDER_LINES USING(ORDER_ID)
GROUP BY CUSTOMER_NAME,ORDER_ID
ORDER BY CUSTOMER_NAME, order_total DESC;


/* 7 */
SELECT 
  CUSTOMER_NAME,
  ORDER_DATE,
  ORDER_ID,
  PRODUCT_CODE,
  QUANTITY,
  PRICE_PAID,
  DESCRIPTION
FROM B_CUSTOMERS
INNER JOIN B_ORDERS USING(CUSTOMER_ID)
INNER JOIN B_ORDER_LINES USING(ORDER_ID) 
INNER JOIN B_PRODUCTS USING(PRODUCT_CODE)
ORDER BY CUSTOMER_NAME, ORDER_ID, PRODUCT_CODE;

