/* 1 */
SELECT 
  FIRST_NAME,
  LAST_NAME,
  MONTHLY_SALARY AS salary
FROM B_EMPLOYEES
WHERE MONTHLY_SALARY = (
  SELECT MIN(MONTHLY_SALARY)
  FROM B_EMPLOYEES 
);

/* 2 */
SELECT 
  LAST_NAME || ', ' || FIRST_NAME AS sales_associate,
  CUSTOMER_NAME,
  CREDIT_LIMIT,
  BALANCE
FROM B_EMPLOYEES e
JOIN B_ORDERS o ON(e.EMPLOYEE_ID = o.SELLER_ID)
JOIN B_CUSTOMERS c ON(o.CUSTOMER_ID = c.CUSTOMER_ID)
WHERE CREDIT_LIMIT - BALANCE > (
  SELECT AVG(CREDIT_LIMIT-BALANCE)
  FROM B_CUSTOMERS
)
ORDER BY LAST_NAME;

/* 3 */
SELECT 
  CUSTOMER_NAME,
  ORDER_ID,
  DAYS(SHIP_DATE) - DAYS(ORDER_DATE) AS days_to_ship
FROM B_CUSTOMERS
JOIN B_ORDERS USING(CUSTOMER_ID)
WHERE DAYS(SHIP_DATE) - DAYS(ORDER_DATE) > (
  SELECT AVG(DAYS(SHIP_DATE) - DAYS(ORDER_DATE))
  FROM B_ORDERS
)
ORDER BY days_to_ship DESC;

/* 4 */
SELECT 
  FIRST_NAME,
  LAST_NAME,
  DEPARTMENT_NAME,
  JOB_TITLE,
  MONTHLY_SALARY
FROM B_EMPLOYEES
JOIN B_DEPARTMENTS USING(DEPARTMENT_CODE)
JOIN B_JOBS USING(JOB_CODE)
WHERE MONTHLY_SALARY > (
  SELECT AVG(MONTHLY_SALARY)
  FROM B_EMPLOYEES
  WHERE DEPARTMENT_CODE = 'MA'
)
ORDER BY MONTHLY_SALARY DESC;

/* 5 */
SELECT 
  JOB_TITLE,
  FIRST_NAME || ' ' || LAST_NAME AS employee_name
FROM B_EMPLOYEES
JOIN B_JOBS USING(JOB_CODE)
WHERE JOB_CODE <> (
  SELECT JOB_CODE
  FROM B_EMPLOYEES
  WHERE LAST_NAME = 'Evans'
)
ORDER BY JOB_TITLE;

/* 6 */
SELECT 
  FIRST_NAME || ' ' || LAST_NAME AS employee_name
FROM B_EMPLOYEES
WHERE DEPARTMENT_CODE = (
  SELECT DEPARTMENT_CODE
  FROM B_DEPARTMENTS
  WHERE DEPARTMENT_NAME = 'Video Games'
)
ORDER BY LAST_NAME;

/* 7 */
SELECT 
  FIRST_NAME || ' ' || LAST_NAME AS employee,
  DEPARTMENT_NAME,
  MONTHLY_SALARY
FROM B_EMPLOYEES
JOIN B_DEPARTMENTS USING(DEPARTMENT_CODE)
WHERE MONTHLY_SALARY > (
  SELECT MONTHLY_SALARY 
  FROM B_EMPLOYEES 
  WHERE LAST_NAME = 'Allan'
) AND DEPARTMENT_CODE = (
  SELECT DEPARTMENT_CODE 
  FROM B_EMPLOYEES
  WHERE LAST_NAME = 'Harper'
)
ORDER BY MONTHLY_SALARY DESC;