/* 1 */
SELECT 
  DEPARTMENT_NAME,
  FIRST_NAME || ' ' || LAST_NAME AS employee,
  JOB_TITLE,
  MONTHLY_SALARY
FROM B_DEPARTMENTS
JOIN B_EMPLOYEES USING (DEPARTMENT_CODE)
JOIN B_JOBS USING (JOB_CODE)
WHERE JOB_TITLE IN (
  SELECT JOB_TITLE
  FROM B_JOBS
  WHERE JOB_TITLE IN('Software Developer', 'Department Manager')
)
ORDER BY DEPARTMENT_NAME 


/* 2 */
SELECT 
  FIRST_NAME,
  LAST_NAME,
  MONTHLY_SALARY AS salary
FROM B_EMPLOYEES
WHERE MONTHLY_SALARY <= ALL (
  SELECT MONTHLY_SALARY
  FROM B_EMPLOYEES
) 


/* 3 */
SELECT 
  DEPARTMENT_NAME,
  FIRST_NAME || ' ' || LAST_NAME AS employee,
  MONTHLY_SALARY
FROM B_DEPARTMENTS
JOIN B_EMPLOYEES USING (DEPARTMENT_CODE)
WHERE MONTHLY_SALARY = ANY (
  SELECT MIN(MONTHLY_SALARY)
  FROM B_EMPLOYEES
  GROUP BY DEPARTMENT_CODE
  HAVING DEPARTMENT_CODE IS NOT NULL
)
ORDER BY DEPARTMENT_NAME, LAST_NAME


/* 4 */
SELECT 
  DEPARTMENT_NAME,
  FIRST_NAME || ' ' || LAST_NAME AS employee,
  MONTHLY_SALARY
FROM B_DEPARTMENTS d
JOIN B_EMPLOYEES e ON (e.DEPARTMENT_CODE = d.DEPARTMENT_CODE)
WHERE MONTHLY_SALARY = (
  SELECT MAX(MONTHLY_SALARY)
  FROM B_EMPLOYEES
  WHERE e.DEPARTMENT_CODE = DEPARTMENT_CODE
)
ORDER BY DEPARTMENT_NAME, LAST_NAME;


/* 5 */
SELECT 
  CUSTOMER_NAME,
  ORDER_ID,
  DAYS(SHIP_DATE) - DAYS(ORDER_DATE) AS DAYS_TO_SHIP
FROM B_CUSTOMERS c
JOIN B_ORDERS o ON(c.CUSTOMER_ID = o.CUSTOMER_ID)
WHERE DAYS(SHIP_DATE) - DAYS(ORDER_DATE) > (
  SELECT AVG(DAYS(SHIP_DATE) - DAYS(ORDER_DATE))
  FROM B_ORDERS
  WHERE c.CUSTOMER_ID = CUSTOMER_ID 
)
ORDER BY DAYS_TO_SHIP DESC;
