/* 1 */
SELECT 
  DECIMAL(AVG(PRICE),4,2) AS AVERAGE,
  DECIMAL(MIN(PRICE),4,2) AS LOWEST,
  DECIMAL(MAX(PRICE),4,2) AS HIGHEST 
FROM H_BOOKS;

/* 2 */
SELECT 
  BOOK_CODE,
  TITLE,
  ON_HAND
FROM H_BOOKS
JOIN H_INVENTORY USING(BOOK_CODE)
WHERE BRANCH_ID = 3
ORDER BY ON_HAND DESC;


/* 3 */
SELECT 
  PUBLISHER_NAME,
  BOOK_CODE,
  TITLE
FROM H_BOOKS
JOIN H_PUBLISHERS USING(PUBLISHER_CODE)
ORDER BY PUBLISHER_NAME;


/* 4 */
SELECT 
  BOOK_CODE,
  TITLE
FROM H_BOOKS
JOIN H_PUBLISHERS USING(PUBLISHER_CODE)
WHERE PRICE > 10 AND CITY = 'Boston'
ORDER BY TITLE DESC;


/* 5 */
SELECT 
  TITLE,
  BOOK_CODE,
  PRICE
FROM H_BOOKS
WHERE PUBLISHER_CODE = 'LB' AND BOOK_TYPE = 'FIC'
ORDER BY TITLE;


/* 6 */
SELECT 
  TITLE,
  b.BOOK_CODE,
  PRICE
FROM H_BOOKS b
JOIN H_INVENTORY i ON(b.BOOK_CODE = i.BOOK_CODE)
JOIN H_BOOK_AUTHORS a ON(b.BOOK_CODE = a.BOOK_CODE)
WHERE BRANCH_ID = 3 AND AUTHOR_ID = 20
ORDER BY TITLE DESC;


/* 7 */
SELECT 
  TITLE,
  AUTHOR_LAST,
  ON_HAND
FROM H_BOOKS b
JOIN H_BOOK_AUTHORS ba ON(b.BOOK_CODE = ba.BOOK_CODE)
JOIN H_AUTHORS a ON(ba.AUTHOR_ID = a.AUTHOR_ID)
JOIN H_INVENTORY i ON(b.BOOK_CODE = i.BOOK_CODE)
WHERE BRANCH_ID = 4 AND PAPERBACK = 'Y'
ORDER BY TITLE;


/* 8 */
SELECT 
  TITLE,
  AUTHOR_LAST
FROM H_BOOKS b
JOIN H_BOOK_AUTHORS ba ON(b.BOOK_CODE = ba.BOOK_CODE)
RIGHT JOIN H_AUTHORS a ON(ba.AUTHOR_ID = a.AUTHOR_ID)
ORDER BY TITLE, SEQUENCE;

/* 9 */
SELECT 
  AUTHOR_LAST,
  AUTHOR_FIRST,
  BOOK_CODE,
  TITLE
FROM H_AUTHORS
RIGHT JOIN H_BOOK_AUTHORS USING(AUTHOR_ID)
JOIN H_BOOKS USING(BOOK_CODE)
WHERE AUTHOR_LAST LIKE 'C%'
ORDER BY AUTHOR_LAST, TITLE;

/* 10 */
SELECT 
  BOOK_TYPE,
  BOOK_CODE,
  TITLE,
  PRICE
FROM H_BOOKS
JOIN H_PUBLISHERS USING(PUBLISHER_CODE)
WHERE PRICE > 10 AND CITY = 'Boston'
ORDER BY BOOK_TYPE DESC, TITLE;

/* 11 */
SELECT 
  TITLE
FROM H_BOOKS
JOIN H_BOOK_AUTHORS USING(BOOK_CODE)
WHERE AUTHOR_ID = 18
ORDER BY TITLE DESC;

/* 12 */
SELECT 
  BOOK_TYPE,
  BOOK_CODE,
  TITLE,
  PRICE
FROM H_BOOKS
WHERE PRICE > ALL(
  SELECT PRICE
  FROM H_BOOKS
  WHERE BOOK_TYPE = 'ART'
)
ORDER BY TITLE DESC;

/* 13 */
SELECT 
  BOOK_TYPE,
  BOOK_CODE,
  TITLE,
  PRICE
FROM H_BOOKS
WHERE PRICE > ANY(
  SELECT PRICE
  FROM H_BOOKS
  WHERE BOOK_TYPE = 'ART'
)
ORDER BY TITLE DESC;

/* 14 */
SELECT 
  BOOK_TYPE,
  TITLE,
  PRICE
FROM H_BOOKS a
WHERE PRICE > (
  SELECT AVG(PRICE)
  FROM H_BOOKS b
  WHERE a.BOOK_TYPE = b.BOOK_TYPE 
)
ORDER BY BOOK_TYPE, PRICE DESC;

/* 15 */
CREATE OR REPLACE VIEW H_JP_VIEW AS
  SELECT  
    BOOK_CODE,
    TITLE,
    BOOK_TYPE,
    PRICE 
  FROM LCPUBLIC.H_BOOKS
  WHERE PUBLISHER_CODE = 'JP'

/* 16 */
SELECT  
  BOOK_TYPE,
  TITLE,
  PRICE 
FROM H_JP_VIEW
WHERE PRICE < 20
ORDER BY BOOK_TYPE DESC;

/* 17 */
SELECT  
  BOOK_TYPE,
  TITLE,
  PRICE 
FROM H_BOOKS hb
WHERE PRICE < 20 AND PUBLISHER_CODE = 'JP'
ORDER BY BOOK_TYPE DESC;

/* 18 */
SELECT  
  BOOK_TYPE,
  COUNT(*) AS NUMBER
FROM H_BOOKS
WHERE BOOK_TYPE IN ('SFI', 'FIC', 'ART')
GROUP BY BOOK_TYPE;
